### ISSUE TITLE
发送图片类消息失败 HTTP 400 Bad Request

### ISSUE THREAD

**Issue by Strawxiguan** [Hoshinonyaruko/Gensokyo-Discord#2]
版本为最新版 Windows amd64
ws连接地址：ws://sanae.youngmoe.com:20020
代理地址已填写，且可正常运行
复刻：
dc端发送：签到
返回代码如下：
2023/12/19 06:53:10 New message content: 签到
2023/12/19 06:53:10 RawMessage: 签到
2023/12/19 06:53:10 MessageID: 18
2023/12/19 06:53:10 GroupID: 1
2023/12/19 06:53:10 MessageType: group
2023/12/19 06:53:10 PostType: message
2023/12/19 06:53:10 SelfID: 1139720487610630206
2023/12/19 06:53:10 Sender: {Straw  2 owner Straw 0 0  0 }
2023/12/19 06:53:10 SubType: normal
2023/12/19 06:53:10 Time: 1702939990
2023/12/19 06:53:10 Avatar: 5e9f58fd1623b6314a34414f2bec35cf
2023/12/19 06:53:10 Echo:
2023/12/19 06:53:10 Message: 签到
2023/12/19 06:53:10 MessageSeq: 0
2023/12/19 06:53:10 Font: 0
2023/12/19 06:53:10 UserID: 2
2023/12/19 06:53:10 RealMessageType: guild
2023/12/19 06:53:10 IsBindedGroupId: true
2023/12/19 06:53:10 IsBindedUserId: true
2023/12/19 06:53:11 Received from onebotv11 server: Action: send_group_msg, Params: {"botqq":"1139720487610630100","channel_id":"","guild_id":"","group_id":"1","message":"[CQ:image,file=http://106.14.218.215:5700/channel_temp/84c44e3dc0f1f5d43caea7a7ce1c2f7c.png]","user_id":"2","context":{},"operation":{}}, Echo: <nil>
2023/12/19 06:53:11 send_group_msg获取到信息类型:guild
2023/12/19 06:53:11 params.message is a string
2023/12/19 06:53:11 通过GetMessageIDByUseridOrGroupid函数获取的message_id: 1186441052765290537
2023/12/19 06:53:11 频道发信息messageText:
2023/12/19 06:53:11 发送消息失败: HTTP 400 Bad Request, {"message": "Invalid Form Body", "code": 50035, "errors": {"embeds": {"0": {"image": {"url": {"_errors": [{"code": "URL_TYPE_INVALID_URL", "message": "Not a well formed URL."}]}}}}}}
若触发文字指令，则不会出现此报错
复刻：
发送内容：随机事件
代码反馈：2023/12/19 06:53:21 New message content: 随机事件
2023/12/19 06:53:21 RawMessage: 随机事件
2023/12/19 06:53:21 MessageID: 21
2023/12/19 06:53:21 GroupID: 1
2023/12/19 06:53:21 MessageType: group
2023/12/19 06:53:21 PostType: message
2023/12/19 06:53:21 SelfID: 1139720487610630206
2023/12/19 06:53:21 Sender: {Straw  2 owner Straw 0 0  0 }
2023/12/19 06:53:21 SubType: normal
2023/12/19 06:53:21 Time: 1702940001
2023/12/19 06:53:21 Avatar: 5e9f58fd1623b6314a34414f2bec35cf
2023/12/19 06:53:21 Echo:
2023/12/19 06:53:21 Message: 随机事件
2023/12/19 06:53:21 MessageSeq: 0
2023/12/19 06:53:21 Font: 0
2023/12/19 06:53:21 UserID: 2
2023/12/19 06:53:21 RealMessageType: guild
2023/12/19 06:53:21 IsBindedGroupId: true
2023/12/19 06:53:21 IsBindedUserId: true
2023/12/19 06:53:21 Received from onebotv11 server: Action: send_group_msg, Params: {"botqq":"1139720487610630100","channel_id":"","guild_id":"","group_id":"1","message":"从前~有一只超级小狐狸，超级小狐狸最喜欢吃超级小红薯~每次都能吃掉好几 个呢~怎么样~是不是知识面提高了呢~？","user_id":"2","context":{},"operation":{}}, Echo: <nil>
2023/12/19 06:53:21 send_group_msg获取到信息类型:guild
2023/12/19 06:53:21 params.message is a string
2023/12/19 06:53:21 通过GetMessageIDByUseridOrGroupid函数获取的message_id: 1186441095962443837
2023/12/19 06:53:21 频道发信息messageText: 从前~有一只超级小狐狸，超级小狐狸最喜欢吃超级小红薯~每次都能吃掉好几个呢~怎么样~是不是知识面提高了呢~？
2023/12/19 06:53:21 New message in guild: 1139572165126140034, channel: 1139572165868523665, content: 从前~有一只超级小 狐狸，超级小狐狸最喜欢吃超级小红薯~每次都能吃掉好几个呢~怎么样~是不是知识面提高了呢~？
2023/12/19 06:53:21 New message content: 从前~有一只超级小狐狸，超级小狐狸最喜欢吃超级小红薯~每次都能吃掉好几个呢~怎么样~是不是知识面提高了呢~？
2023/12/19 06:53:21 发送成功回执: {"data":{"message_id":0},"echo":null,"message":"","retcode":0,"status":"ok"}
2023/12/19 06:53:21 RawMessage: 从前~有一只超级小狐狸，超级小狐狸最喜欢吃超级小红薯~每次都能吃掉好几个呢~怎么样~是不是知识面提高了呢~？
截图：
报错截图如下
![76c91c5c98f00124134e870c001f68a3](https://github.com/Hoshinonyaruko/Gensokyo-Discord/assets/127127787/90f166fb-f13e-4530-adf1-821b56c71afd)
发送成功如下
![image](https://github.com/Hoshinonyaruko/Gensokyo-Discord/assets/127127787/2eda2713-f45d-460a-8c7c-ae0446a4129a)

不知道此现象是因个人原因引起，还是因为其他原因所致

**Comment by Hoshinonyaruko** [comment]
在beta3中已经修复,感谢反馈!同时增加了
url图片开启url_pic_transfer可秒发成功
可更快的发送url图片
